#   you need to download a <<REST Client>> extension in vscode 



#-----------------------------AUTH ENDPOINT-------------------------------------------------------

### ------------------REGISTER
POST http://localhost:5000/auth/register HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "username": "jojo",
    "password": "12345678",
    "confirmPassword": "12345678"
}

### --------------------LOGIN
POST http://localhost:5000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "12345678"
}


### --------------------LOGOUT
GET http://localhost:5000/auth/logout HTTP/1.1


### --------------------REFRESH
GET http://localhost:5000/auth/refresh HTTP/1.1


### --------------------VERIFY EMAIL
GET http://localhost:5000/auth/email/verify/6769d278f3c69526addeafce HTTP/1.1


### --------------------FORGOT PASSWORD EMAIL SEND
POST http://localhost:5000/auth/password/forgot HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
}


### --------------------RESET PASSWORD
POST http://localhost:5000/auth/password/reset HTTP/1.1
content-type: application/json

{
    "verificationCode": "",
    "password": "12345678"
}


#-----------------------------USER ENDPOINT-------------------------------------------------------

### ----------------GET USER
GET http://localhost:5000/user/ HTTP/1.1
### ----------------GET USER FOR SIDEBAR

GET http://localhost:5000/user/conversation HTTP/1.1


#-----------------------------SESSION ENDPOINT-------------------------------------------------------

### ----------------GET ALL SESSIONS
GET http://localhost:5000/session/ HTTP/1.1

### -----------------DELETE SESSION
DELETE http://localhost:5000/session/:id/ HTTP/1.1



#-----------------------------MESSAGE ENDPOINT-------------------------------------------------------


### ----------------GET MESSAGE
GET http://localhost:5000/message/:id HTTP/1.1
messageRoutes.get("/:id",getMessages)
messageRoutes.post("/send/:id",sendMessage)

### ----------------POST MESSAGE
POST http://localhost:5000/message/send/:id HTTP/1.1
content-type: application/json

{
    "content": "",
}










